### ISSUE TITLE
Shell option for use with provisioners

### ISSUE THREAD

**Issue by dgengtek** [NexusSW/kitchen-lxd_sling#11]
I have been using kitchen-salt (0.2.3) with kitchen-lxd_sling (0.5.5) and kitchen-salt would fail when passing the provisioning command to the lxd driver which uses lxc exec to pass the commands to the container.

lxc-execute {-n name} [-d] [-f config_file] [-s KEY=VAL] [-- command]

The binary is not using a shell by default and is unable to handle the globs and chained commands. Is there an easy way to specify a shell the driver can use for lxc-execute so the kitchen-salt provisioner does not fail?

Thanks

**Comment by thewyzard44** [comment]
The quickest answer would only work if your container image has sshd enabled and is routable (I haven't dug into the new port forwarding features, yet).  But if you set up your kitchen file like this

```
driver:
  name: lxd
  ssh_login:
    username: <defaults to root>
    public_key: <local path to file: ~/.ssh/id_rsa.pub>

transport: ssh
```
then kitchen-salt will use ssh to get into the container and provision (and that has a shell)


If ssh is not an option, my transport actually wraps everything with a hardcoded `bash -c 'cmd'`

https://github.com/NexusSW/kitchen-lxd_sling/blob/35a64b1aced49c386d405e46ae7562f5da78c6c2/lib/kitchen/transport/lxd.rb#L44-L48

which results in a command like `lxc exec containername -- bash -c 'some multiword command && chain'`

I could make that configurable if, perhaps, a different shell would be useful?

**Comment by dgengtek** [comment]
Thank you for your quick response. It seems like there is an issue with my environment. Your snippet shows that the driver is not the issue.
